### PR TITLE
docs: sc-goodies

### PR DESCRIPTION
**Pull request by dimaguy**
I have not tried to build the documentation, but I've followed about the same structure as other files so should be fine.
I haven't had the patience/time to get imagery of the mod, so I've not done trees and grass documentation given it's appeal is solely aesthetic.
I also can't ensure that the popcorn description is 100% accurate as I've just spent 5 minutes trying it out in creative/survival in single player

### CODE REVIEW

**Comment by Lemmmy** [comment]
You should try and build this, this is not valid markdown

I will probably wait until SwitchCraftCC/sc-goodies#20 is merged before looking at this, but I will add the the images to this PR later since I already have renders for most of them. I have a lot of comments to add which I will do in a review when I'm not on mobile

**Comment by dimaguy** [comment]
I've attempted to preview and build it, but no error came up whatsoever. I admit there might be places where I could apply it better, like in iron chests with a table. but it mostly renders as expected.
I've also noticed that iron barrels is incoming, and I was planning to make a draft PR to cover it if this one got merged.

**Comment by Lemmmy** [comment]
Thanks for making a start on this. Is it ok if I edit directly on top of the PR?

**Comment by dimaguy** [comment]
> Thanks for making a start on this. Is it ok if I edit directly on top of the PR?

That is absolutely fine, I was just going for a starter myself since it was better than no docs at all

**Comment by Lemmmy** [comment]
Thank you!

**Pull request merged**
