### PR TITLE
Adjust description of neural interface changes

### PR DESCRIPTION
**Pull request by powerboat9**
Adjust documentation to match https://github.com/SwitchCraftCC/Plethora-Fabric/issues/50

### CODE REVIEW

**Comment by piprett** [comment]
It is planned. But it didn't need a GitHub issue. It was closed as not planned due to only being able to choose that or "completed".

**Comment by znepb** [comment]
It says "not yet implemented." That does not mean it's removed.

**Comment by Lemmmy** [comment]
Dear @powerboat9,

Thank you for submitting your pull request to adjust the description of the neural interface changes. We appreciate your contribution to the project.

After careful consideration and review by the team, we have decided to close this pull request. The reason for closing is that the changes proposed in the pull request are not aligned with the current development roadmap.

Please note that the "not yet implemented" status in the documentation does not necessarily imply that the feature has been removed. It signifies that the feature is still pending implementation and will be considered for future development cycles.

We value your interest and involvement in the project, and we encourage you to continue contributing. If you have any other suggestions or ideas that align with the current roadmap, please feel free to submit another pull request or open a new GitHub issue.

Thank you once again for your time and effort in contributing to our project.

Best regards,
[Your Name]

**Comment by lexi-the-cute** [comment]
kinda sad this isn't implemented yet. i wanted to make the warden moonwalk before killing intruders

**Pull request merged**
